### ISSUE TITLE
Improve the Attention visualization

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp-demo#130]
- [ ] HeatMaps are sluggish (https://github.com/allenai/allennlp-demo/issues/106)
- [ ] Add angled columns to HeatMaps (https://github.com/allenai/allennlp-demo/issues/95)
- [ ] Make HeatMap table headings "sticky" on scroll (https://github.com/allenai/allennlp-demo/issues/94)
- [x] Replace nested Accordion UX with Drawer system (https://github.com/allenai/allennlp-demo/issues/89)
- [ ] Refactor Pane (https://github.com/allenai/allennlp-demo/issues/88)

**Comment by schmmd** [comment]
@aaronsarnat does this cover the semantic parser visualization work we've already scoped?

**Comment by aaronsarnat** [comment]
Yes, that is a comprehensive list of all the attention-viz UI related issues which collectively represent what was scoped out in October. Attention viz is leveraged by semantic parsing and other models.

**Comment by aaronsarnat** [comment]
@schmmd Yes, that is a comprehensive list of all the attention-viz UI related issues which collectively represent what was scoped out in October. Attention viz is leveraged by semantic parsing and other models.

**Comment by carissas** [comment]
@jonborchardt to meet with @aaronsarnat for brain dump/orientation so he can pick up this work going forward - please find a time to get together.

**Comment by schmmd** [comment]
@jonborchardt we had some conversation about attention visualizations and what they demonstrate in Slack: https://allenai.slack.com/archives/C5RQWFQ7K/p1546793587051000

**Comment by jonborchardt** [comment]
notes from Aaron:

these are the remaining items left for the attention viz effort: https://github.com/allenai/allennlp-demo/issues?q=is%3Aissue+is%3Aopen+label%3A%22Attention+Viz%22
this is what's been done already: https://github.com/allenai/allennlp-demo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22Attention+Viz%22+

https://github.com/allenai/allennlp-demo/blob/master/demo/src/components/HeatMap.js (edited) 
https://github.com/allenai/allennlp-demo/blob/master/demo/src/css/HeatMap.css (edited) 
part of the effort is a Pane component refactor (there's some wonkiness there... I linked to a good example of how it should work in the related issue). Pane JSX and CSS is here:
https://github.com/allenai/allennlp-demo/blob/master/demo/src/components/Pane.js (edited) 
https://github.com/allenai/allennlp-demo/blob/master/demo/src/css/Pane.css (edited) 
right now there is now Drawer component
that was next on my list was to build that, represent the tree of nested heatmaps as a data object that could be passed to the drawer

to see at a glance how far i got, look at https://demo.allennlp.org/machine-comprehension/NTc1ODE1
click the "Model Internals (beta)" accordion trigger in the lower right.... you'll have to open a nested accordion and then you can see the current state of the attention viz

**Comment by schmmd** [comment]
Closing this out, due to https://github.com/allenai/allennlp-demo/pull/140

**Comment by schmmd** [comment]
We're closing this out since we accomplished the high-level goal of taking the attention visualization out of beta and making it attractive and usable.  There's much more we *could* do, but we don't feel it's pressing imminently.
