### ISSUE TITLE
Replace nested Accordion UX with Drawer system

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp-demo#89]
This task is based on the recent aspirational design for the new Attention Visualization:

[![image](https://user-images.githubusercontent.com/8367927/46327384-3d6be100-c5b6-11e8-8b7b-d50ce3ee2145.png)](https://drive.google.com/file/d/1WoCAjcUfT0SvZY2aNJuhoFeXGgnvo8ZR/view?usp=sharing)

---

**Sub-tasks**

- [ ] 1. [Refactor `<Pane />` (#88)](https://github.com/allenai/allennlp-demo/issues/88)
- [ ] 2. Build resizable and toggle-able `<Drawer />` component
- [ ] 3. Add a `<DrawerTrigger />` component that is anchored to the bottom of the output pane
- [ ] 4. Recreate `<HeatMap />` component tree as data object
- [ ] 5. Remove `<Collapsible />` component and NPM dependency from demo
- [ ] 6. Add Google-Drive-style "file/folder explorer" and breadcrumbs navigation

---

Re: Item 4, "Model Internals" `<Drawer />` component will probably live outside the model component as a child of `<App />`. Thus, we will need to send the attention visualization tree to `<Drawer />` via a callback function passed down as props from `<App />`.

**Comment by schmmd** [comment]
Closing as it's from 2018.
